### ISSUE TITLE
URL signature expired

### ISSUE THREAD

**Issue by haochengxia** [fanlai0990/CS598#10]
Sept 18	[The Llama 3 Herd of Models](https://scontent-sea1-1.xx.fbcdn.net/v/t39.2365-6/453304228_1160109801904614_7143520450792086005_n.pdf?_nc_cat=108&ccb=1-7&_nc_sid=3c67a6&_nc_ohc=PC3CtquZIecQ7kNvgGAswkt&_nc_ht=scontent-sea1-1.xx&oh=00_AYAsVI8tP34-1q_lzl-8hAFCp0g-Jr-sQmwN1PC0IpXEmA&oe=66B5E347) (Sec 1-4, Required) -> URL signature expired

Can we read [arXiv version](https://arxiv.org/abs/2407.21783) directly?

**Comment by fanlai0990** [comment]
Thank you Haocheng! We fixed it.
